version: '3'

services:
  mysql:
    image: mysql:8.0.23
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_DATABASE=money_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/config:/etc/mysql/conf.d
    healthcheck:
      test: "exit 0"
    
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=admin
      - PMA_PASSWORD=password
    volumes:
      - .docker/phpmyadmin/config:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql